apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: dm-demo
    namespace: default
  spec:
    replicas: 5
    selector:     # Not sure if I need this
      matchLabels: 
        app: dm-demo
    strategy:
      rollingUpdate:
        maxUnavailable: 1
    template:
      metadata:
        labels:
          app: dm-demo
      spec:
        containers:
        - name: dm-demo
          image: image-registry.openshift-image-registry.svc:5000/default/abn-validator
          livenessProbe:
            httpGet:
              path: /alivez
              port: 10000
          ports: 
          - containerPort: 10000
          resources:
            requests:
              cpu: 0.5
              memory: 1Gi
- apiVersion: v1
  kind: Service
  metadata:
    name: dm-demo
    namespace: default
    labels:
      app: dm-demo
  spec:
    selector:
      app: dm-demo
    ports:
    - port: 10000
      targetPort: 10000
# - apiVersion: route.openshift.io/v1
#   kind: Route
#   metadata:
#     name: dm-demo
#     namespace: default
#     labels:
#       app: dm-demo
#   spec:
#     host: dm-demo-default.apps.cluster-anz-f723.anz-f723.openshiftworkshop.com
#     subdomain: ''
#     to:
#       kind: Service
#       name: dm-demo
#       weight: 100
#     port:
#       targetPort: 10000
#     wildcardPolicy: None
