kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: abn-validator
  namespace: default
  labels:
    app: abn-validator
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      annotations: null
      from:
        kind: DockerImage
        name: 'bryonbaker/abn-validator:0.7'
      generation: 1
      importPolicy: {}
      referencePolicy:
        type: Source